version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  golang-middleware-env:
    lang: golang-middleware
    handler: ./golang-middleware-env
    image: ${DOCKER_USER:-superscan}/golang-middleware-env:latest
    readonly_root_filesystem: true
